# Generated by Django 4.2.21 on 2025-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_refreshsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshsession',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
